name: Deploy to GitHub Pages

on:
  push:
    branches:
      -  gh-pages 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
	@@ -23,9 +19,14 @@ jobs:

      - name: Install dependencies
        run: npm install
        working-directory: ./my-app

      - name: Build project
        run: npm run build
        working-directory: ./my-app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./my-app/build
