echo "name: Deno CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-
      - name: Run Deno
        run: deno test --unstable --allow-net
" > path/to/deno.yml
